language: ruby
rvm:
- 2.3.0
addons:
  postgresql: '9.4'
before_script:
- psql -c 'create database travis_ci_test;' -U postgres
- cp config/database.yml.travis config/database.yml
deploy:
  provider: heroku
  api_key:
    secure: gTAgKCAX5A+ZK+JSoBCeRiC1LV7cxBHWxZc5iWECYGM0taPIpLVS5cnD0s2kDSuQ6/s4I7zEEgt1LIFqSbZaPbdsTHaIQnEbnyCUitl3RoJb/SYZfF/oCYMUY1LPb8PxKU9qpCJHkmt5PUcLhSG3MnREqCzCsM6T+wkv7H7w/pFrlHUgN9QB1IWSgugC8iWhYKxoKxnvskIZJZ+20WEQhkPI0oru1+dEecdGOL8xvfW1QG7L3k5/karSwjWfhSVxnyMpFN01tsHRIuop4IradLFhFHLOOdxvnNU3asCOL9u1BqSq/g5w/OQ1nVVAa/CoELhf/YlkVAkGQOxDspB6OrlOVhFAKI+yZ4mQ4CxeOviLio+QUpiVyzM7JAtjXlAlvUyoyPFXQOFZJSe+hpmpw1IUEQYVEofOnAZhCKsYVH/jRylljV0blJWgQr6nugGOP/Ai4PgfFwlGbjZUzUb+kRcziwHxDAuC2ItJin5eeBado4dmG4WkPlWBtN2Xx0n5pJt0eOhAept5Hwj9QksEug3UkNswDsQa5zfnU6ETh++/IJAaMMDdBHiHoQfQb0V4bnndoLo4FNoWNhAvcS5L46hNCoHspbJU7wzL5dXg7kedHdLZC6HqeyILGRX53ZNMG4MrRSAKZoqOfLSF9u74YrM9P0T2Dl9AfTQUPjArG6Q=
  app: sv886slack
  on:
    repo: sv886/slack
  run:
  - "rake db:migrate"
